"""Build web/engine.js: the openppc package and the sample files, as one script the page loads.

Run it after changing anything in openppc/ or examples/:

    python tools/build_web.py

tests/test_webapi.py fails when web/engine.js is out of date.
"""
import base64
import json
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "web" / "engine.js"
SAMPLES = ("search_terms_acme.csv", "keywords_acme.csv", "account_acme.json", "account_structure_acme.json",
           "ai_audit_sample.md")


def templates():
    """The template list, so the Templates page shows it before the engine has loaded."""
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from openppc.templates import TEMPLATES
    return [{"name": t.NAME, "module": t.__name__.rsplit(".", 1)[1], "title": t.TITLE, "tier": t.TIER,
             "input": t.INPUT, "summary": t.SUMMARY} for t in TEMPLATES.values()]


SAMPLE_PATH = "/uploads/search_terms_acme.csv"  # where the app puts the sample export in the engine's files


def sample():
    """The sample's results, computed here by the same engine the browser runs, so "Try the sample" shows them at
    once while the engine downloads. The app uses them only for the untouched sample, never for your own files."""
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from openppc import webapi
    text = (ROOT / "examples" / "ai_audit_sample.md").read_text(encoding="utf-8")
    with tempfile.TemporaryDirectory() as folder:
        path = str(Path(folder) / "search_terms_acme.csv")
        shutil.copyfile(ROOT / "examples" / "search_terms_acme.csv", path)
        info = json.loads(webapi.inspect_file(path))
        paths = json.dumps([path])
        found = {"meta": json.loads(webapi.meta()), "info": info, "count": webapi.count_numbers(text, paths),
                 "check": json.loads(webapi.check(text, paths, "home-services")),
                 "audit": json.loads(webapi.audit("search-term-waste", path, "home-services", info["min_cost"], ""))}
    found["audit"]["token"] = None  # a token names an audit kept in the browser engine's memory: the app runs one there
    out = json.dumps(found, sort_keys=True)
    assert folder not in out, "a sample result names the build's folder"
    return found


def bundle():
    files = {p.relative_to(ROOT).as_posix(): p.read_text(encoding="utf-8")
             for p in sorted((ROOT / "openppc").rglob("*.py"))}
    samples = {name: base64.b64encode((ROOT / "examples" / name).read_bytes()).decode("ascii")
               for name in SAMPLES}
    payload = json.dumps({"files": files, "samples": samples, "templates": templates(), "sample": sample(),
                          "sample_path": SAMPLE_PATH}, sort_keys=True, separators=(",", ":"))
    return ("// Generated by tools/build_web.py from openppc/ and examples/. Do not edit by hand.\n"
            f"globalThis.OPENPPC_BUNDLE = {payload};\n")


def main():
    OUT.write_text(bundle(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
