"""Build web/engine.js: the openppc package and the sample files, as one script the page loads.

Run it after changing anything in openppc/ or examples/:

    python tools/build_web.py

tests/test_webapi.py fails when web/engine.js is out of date.
"""
import base64
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "web" / "engine.js"
SAMPLES = ("search_terms_acme.csv", "keywords_acme.csv", "account_acme.json", "account_structure_acme.json",
           "ai_audit_sample.md")


def templates():
    """The template list, so the Templates page shows it before the engine has loaded."""
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from openppc.templates import TEMPLATES
    return [{"name": t.NAME, "module": t.__name__.rsplit(".", 1)[1], "title": t.TITLE, "tier": t.TIER,
             "input": t.INPUT, "summary": t.SUMMARY} for t in TEMPLATES.values()]


def bundle():
    files = {p.relative_to(ROOT).as_posix(): p.read_text(encoding="utf-8")
             for p in sorted((ROOT / "openppc").rglob("*.py"))}
    samples = {name: base64.b64encode((ROOT / "examples" / name).read_bytes()).decode("ascii")
               for name in SAMPLES}
    payload = json.dumps({"files": files, "samples": samples, "templates": templates()}, sort_keys=True, separators=(",", ":"))
    return ("// Generated by tools/build_web.py from openppc/ and examples/. Do not edit by hand.\n"
            f"globalThis.OPENPPC_BUNDLE = {payload};\n")


def main():
    OUT.write_text(bundle(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
